# Generated by Django 5.0.7 on 2024-07-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=225)),
                ('fields', models.CharField(max_length=225)),
                ('permissions', models.CharField(max_length=225)),
            ],
        ),
    ]
